[2023-11-04T03:39:21.903+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:31:06.668121+00:00/task_id=merge_and_transform_utilities permission to 509
[2023-11-04T03:39:21.904+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:31:06.668121+00:00/task_id=merge_and_transform_utilities permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:31:06.668121+00:00/task_id=merge_and_transform_utilities'
[2023-11-04T03:39:21.929+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:31:06.668121+00:00/task_id=merge_and_transform_utilities permission to 509
[2023-11-04T03:39:21.930+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:31:06.668121+00:00/task_id=merge_and_transform_utilities permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:31:06.668121+00:00/task_id=merge_and_transform_utilities'
[2023-11-04T03:39:21.961+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: col_api_etl.merge_and_transform_utilities manual__2023-11-04T03:31:06.668121+00:00 [queued]>
[2023-11-04T03:39:21.969+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: col_api_etl.merge_and_transform_utilities manual__2023-11-04T03:31:06.668121+00:00 [queued]>
[2023-11-04T03:39:21.969+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-04T03:39:21.981+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): merge_and_transform_utilities> on 2023-11-04 03:31:06.668121+00:00
[2023-11-04T03:39:21.987+0000] {standard_task_runner.py:57} INFO - Started process 44918 to run task
[2023-11-04T03:39:21.987+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-11-04T03:39:21.991+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'col_api_etl', 'merge_and_transform_utilities', 'manual__2023-11-04T03:31:06.668121+00:00', '--job-id', '1316', '--raw', '--subdir', 'DAGS_FOLDER/col_api_etl.py', '--cfg-path', '/tmp/tmpvejo8w5k']
[2023-11-04T03:39:21.992+0000] {standard_task_runner.py:85} INFO - Job 1316: Subtask merge_and_transform_utilities
[2023-11-04T03:39:22.031+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:31:06.668121+00:00/task_id=merge_and_transform_utilities permission to 509
[2023-11-04T03:39:22.032+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:31:06.668121+00:00/task_id=merge_and_transform_utilities permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:31:06.668121+00:00/task_id=merge_and_transform_utilities'
[2023-11-04T03:39:22.034+0000] {task_command.py:415} INFO - Running <TaskInstance: col_api_etl.merge_and_transform_utilities manual__2023-11-04T03:31:06.668121+00:00 [running]> on host 0bcf85c4b011
[2023-11-04T03:39:22.234+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='col_api_etl' AIRFLOW_CTX_TASK_ID='merge_and_transform_utilities' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T03:31:06.668121+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-04T03:31:06.668121+00:00'
[2023-11-04T03:39:32.736+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-04T03:39:32.751+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=col_api_etl, task_id=merge_and_transform_utilities, execution_date=20231104T033106, start_date=20231104T033921, end_date=20231104T033932
[2023-11-04T03:39:32.793+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
