[2023-11-04T03:25:46.336+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:16:58.704133+00:00/task_id=merge_and_transform_transportation permission to 509
[2023-11-04T03:25:46.336+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:16:58.704133+00:00/task_id=merge_and_transform_transportation permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:16:58.704133+00:00/task_id=merge_and_transform_transportation'
[2023-11-04T03:25:46.361+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:16:58.704133+00:00/task_id=merge_and_transform_transportation permission to 509
[2023-11-04T03:25:46.362+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:16:58.704133+00:00/task_id=merge_and_transform_transportation permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:16:58.704133+00:00/task_id=merge_and_transform_transportation'
[2023-11-04T03:25:46.395+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: col_api_etl.merge_and_transform_transportation manual__2023-11-04T03:16:58.704133+00:00 [queued]>
[2023-11-04T03:25:46.403+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: col_api_etl.merge_and_transform_transportation manual__2023-11-04T03:16:58.704133+00:00 [queued]>
[2023-11-04T03:25:46.404+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-04T03:25:46.416+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): merge_and_transform_transportation> on 2023-11-04 03:16:58.704133+00:00
[2023-11-04T03:25:46.421+0000] {standard_task_runner.py:57} INFO - Started process 38775 to run task
[2023-11-04T03:25:46.422+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-11-04T03:25:46.425+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'col_api_etl', 'merge_and_transform_transportation', 'manual__2023-11-04T03:16:58.704133+00:00', '--job-id', '1307', '--raw', '--subdir', 'DAGS_FOLDER/col_api_etl.py', '--cfg-path', '/tmp/tmpa0mb54fz']
[2023-11-04T03:25:46.426+0000] {standard_task_runner.py:85} INFO - Job 1307: Subtask merge_and_transform_transportation
[2023-11-04T03:25:46.463+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:16:58.704133+00:00/task_id=merge_and_transform_transportation permission to 509
[2023-11-04T03:25:46.464+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:16:58.704133+00:00/task_id=merge_and_transform_transportation permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=col_api_etl/run_id=manual__2023-11-04T03:16:58.704133+00:00/task_id=merge_and_transform_transportation'
[2023-11-04T03:25:46.466+0000] {task_command.py:415} INFO - Running <TaskInstance: col_api_etl.merge_and_transform_transportation manual__2023-11-04T03:16:58.704133+00:00 [running]> on host 0bcf85c4b011
[2023-11-04T03:25:46.661+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='col_api_etl' AIRFLOW_CTX_TASK_ID='merge_and_transform_transportation' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T03:16:58.704133+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-04T03:16:58.704133+00:00'
[2023-11-04T03:25:55.986+0000] {logging_mixin.py:151} INFO - +----+----+-----+
|City|Type|Price|
+----+----+-----+
+----+----+-----+
[2023-11-04T03:25:58.164+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-04T03:25:58.175+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=col_api_etl, task_id=merge_and_transform_transportation, execution_date=20231104T031658, start_date=20231104T032546, end_date=20231104T032558
[2023-11-04T03:25:58.236+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
